### ISSUE TITLE
Getting TypeError: send() got an unexpected keyword argument 'timeout' trying simple tasks

### ISSUE THREAD

**Issue by DnPlas** [gtsystem/lightkube#12]
I get `send() got an unexpected keyword argument 'timeout'` messages when trying to patch or list resources, but this might affect other things.

#### Possible cause
This behaviour started today and might be related to the latest httpx release [0.20.0](https://github.com/encode/httpx/releases/tag/0.20.0).

#### Steps to reproduce
This happens after installing the `lightkube` pypi package, letting `pip` solve dependencies.

```bash
$ pip install lightkube --no-cache
```
Then try listing nodes

```bash
Python 3.8.10 (default, Sep 28 2021, 16:10:42) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from lightkube import Client
>>> from lightkube.resources.core_v1 import Node
>>> client = Client()
>>> for node in client.list(Node):
...     print(node.metadata.name)
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/lightkube/core/generic_client.py", line 239, in list
    resp = self.send(req)
  File "/usr/local/lib/python3.8/dist-packages/lightkube/core/generic_client.py", line 204, in send
    return self._client.send(req, stream=stream, timeout=self._watch_timeout if stream else None)
TypeError: send() got an unexpected keyword argument 'timeout'
```
#### Workaround
I workaround this issue downgrading to 0.18.1.

#### My setup
Ubuntu 20.04
Python 3.8.10
pip 21.3
microk8s 1.21/stable

**Comment by gtsystem** [comment]
It should be now fixed in 0.8.1
